name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      parallel: 4
    runs-on: ubuntu-latest
    steps:
      # Check out the code
      - uses: actions/checkout@v2
      # Set up Python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      # Retrieve metadata about the workflow run
      - name: Get metadata
        id: metadata
        uses: actions/meta@v1
      # Save the IP address to a file
      - name: Save IP address
        run: echo "The IP address of the VM is ${{ steps.metadata.outputs.ip }}" >> ip_address.txt
      # Install dependencies
      - run: pip install -r requirements.txt
      # Run the server
      - run: python server.py
